export default [
  {
    _id: '5ff56b2752c48f2c0bbcb4a2',
    index: 0,
    guid: 'f7ac2da1-6f3e-414b-b5a2-e155a19548bb',
    isActive: false,
    balance: '$1,968.20',
    picture: 'http://placehold.it/32x32',
    age: 31,
    eyeColor: 'blue',
    name: 'Maynard Harrell',
    gender: 'male',
    company: 'ZAPHIRE',
    email: 'maynardharrell@zaphire.com',
    phone: '+1 (840) 442-3726',
    address: '336 Kenmore Court, Fairlee, Arkansas, 1198',
    about:
      'Nostrud velit nostrud occaecat sunt. Occaecat velit labore fugiat aliquip sunt consectetur. Voluptate tempor ut aute exercitation deserunt proident laboris est consectetur officia tempor. Do commodo pariatur cillum mollit consectetur ex labore. In adipisicing ad mollit tempor reprehenderit consectetur sit eiusmod excepteur minim occaecat excepteur do nulla. Laboris exercitation sint veniam eiusmod qui sunt.\r\n',
    registered: '2019-12-26T04:41:07 -08:00',
    latitude: -87.453593,
    longitude: -128.521673,
    tags: ['est', 'ea', 'labore', 'ea', 'consectetur', 'enim', 'adipisicing'],
    friends: [
      {
        id: 0,
        name: 'Geraldine Blankenship',
      },
      {
        id: 1,
        name: 'Alma Valdez',
      },
      {
        id: 2,
        name: 'Gwendolyn Clemons',
      },
    ],
    greeting: 'Hello, Maynard Harrell! You have 4 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5ff56b270226d501db123760',
    index: 1,
    guid: 'c5bf892f-ed62-4d52-ab13-cb79281ee0f1',
    isActive: false,
    balance: '$2,661.52',
    picture: 'http://placehold.it/32x32',
    age: 37,
    eyeColor: 'brown',
    name: 'Miranda Saunders',
    gender: 'female',
    company: 'ZOINAGE',
    email: 'mirandasaunders@zoinage.com',
    phone: '+1 (909) 464-3122',
    address: '523 Losee Terrace, Fairfield, Maryland, 5061',
    about:
      'Id adipisicing ea dolore exercitation minim et exercitation ipsum enim do ullamco qui incididunt et. Pariatur eiusmod nostrud quis magna laboris laboris. Do in veniam sunt non dolor duis dolor sit. Id laborum cillum sint commodo exercitation. Incididunt occaecat deserunt fugiat ea minim.\r\n',
    registered: '2014-10-29T08:05:54 -08:00',
    latitude: 48.018504,
    longitude: 100.967107,
    tags: [
      'nisi',
      'nostrud',
      'aliqua',
      'est',
      'anim',
      'cillum',
      'exercitation',
    ],
    friends: [
      {
        id: 0,
        name: 'Katie Hays',
      },
      {
        id: 1,
        name: 'Ella Mullen',
      },
      {
        id: 2,
        name: 'Greene Johnson',
      },
    ],
    greeting: 'Hello, Miranda Saunders! You have 7 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '5ff56b2793acaf86d476a110',
    index: 2,
    guid: 'f0114348-0f8d-4fba-ba75-fdd9a3a5510c',
    isActive: false,
    balance: '$1,268.76',
    picture: 'http://placehold.it/32x32',
    age: 26,
    eyeColor: 'green',
    name: 'Newton Wilkins',
    gender: 'male',
    company: 'ZENTIX',
    email: 'newtonwilkins@zentix.com',
    phone: '+1 (817) 575-3108',
    address: '915 Hooper Street, Thomasville, Marshall Islands, 8966',
    about:
      'Tempor esse laborum cupidatat pariatur duis. Mollit voluptate culpa pariatur cillum dolore nulla occaecat laboris cupidatat laboris elit cillum qui. Quis eiusmod dolore reprehenderit excepteur velit. Cillum magna et fugiat sunt ex exercitation labore quis irure reprehenderit.\r\n',
    registered: '2015-09-30T11:48:41 -08:00',
    latitude: 60.575184,
    longitude: -3.802146,
    tags: ['dolore', 'ex', 'ullamco', 'mollit', 'qui', 'ea', 'laborum'],
    friends: [
      {
        id: 0,
        name: 'Bender Reeves',
      },
      {
        id: 1,
        name: 'Alyson Cabrera',
      },
      {
        id: 2,
        name: 'Adrian Rowe',
      },
    ],
    greeting: 'Hello, Newton Wilkins! You have 1 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5ff56b2771094ef4bdd3c808',
    index: 3,
    guid: 'abe5cbc4-517a-4a6a-9aa3-9406a2dec8c1',
    isActive: true,
    balance: '$1,549.92',
    picture: 'http://placehold.it/32x32',
    age: 32,
    eyeColor: 'green',
    name: 'Joseph Hatfield',
    gender: 'male',
    company: 'COMCUBINE',
    email: 'josephhatfield@comcubine.com',
    phone: '+1 (972) 553-2427',
    address: '872 Fane Court, Centerville, Arizona, 3822',
    about:
      'Proident non ipsum voluptate nulla id sit enim reprehenderit amet laboris proident. Fugiat culpa ullamco fugiat nisi. Laboris ipsum aliquip do aliqua irure ad non anim. Commodo duis sunt fugiat Lorem Lorem qui sint.\r\n',
    registered: '2016-05-05T03:40:16 -08:00',
    latitude: 8.66596,
    longitude: -5.762517,
    tags: [
      'laborum',
      'excepteur',
      'aliqua',
      'pariatur',
      'laboris',
      'eu',
      'irure',
    ],
    friends: [
      {
        id: 0,
        name: 'Wynn Heath',
      },
      {
        id: 1,
        name: 'Autumn Snow',
      },
      {
        id: 2,
        name: 'Gretchen Barr',
      },
    ],
    greeting: 'Hello, Joseph Hatfield! You have 10 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5ff56b27718913c6161ff6ef',
    index: 4,
    guid: '8cd723e6-6ae5-4fd0-9d71-444e862a96cd',
    isActive: false,
    balance: '$3,919.36',
    picture: 'http://placehold.it/32x32',
    age: 21,
    eyeColor: 'brown',
    name: 'James Simpson',
    gender: 'male',
    company: 'ZIZZLE',
    email: 'jamessimpson@zizzle.com',
    phone: '+1 (894) 485-3645',
    address: '345 Eastern Parkway, Roosevelt, Northern Mariana Islands, 6640',
    about:
      'Ea nisi ullamco ipsum quis consequat dolor et ea. Incididunt pariatur proident labore minim proident Lorem commodo in. Do ex qui nulla exercitation laboris proident. Occaecat dolore pariatur incididunt anim excepteur dolor. Laboris pariatur aute duis sit cillum in. Occaecat nisi sunt non labore reprehenderit cillum ea dolore ut.\r\n',
    registered: '2014-02-03T06:53:51 -08:00',
    latitude: 33.396364,
    longitude: -40.422572,
    tags: [
      'cupidatat',
      'ad',
      'amet',
      'esse',
      'reprehenderit',
      'proident',
      'nostrud',
    ],
    friends: [
      {
        id: 0,
        name: 'Julie Wilkerson',
      },
      {
        id: 1,
        name: 'Perez Odom',
      },
      {
        id: 2,
        name: 'Alta Kane',
      },
    ],
    greeting: 'Hello, James Simpson! You have 10 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '5ff56b27b84dd70ed8ec1271',
    index: 5,
    guid: '24a307ba-cff7-422d-bcaf-a39ccde03f1f',
    isActive: true,
    balance: '$3,932.89',
    picture: 'http://placehold.it/32x32',
    age: 29,
    eyeColor: 'green',
    name: 'Gallegos Good',
    gender: 'male',
    company: 'STUCCO',
    email: 'gallegosgood@stucco.com',
    phone: '+1 (833) 536-3034',
    address: '824 Hemlock Street, Alafaya, Washington, 3553',
    about:
      'Qui minim labore esse deserunt. Officia velit consequat laboris id minim aute anim est aute. Aliqua sit ut deserunt proident officia. Sint ipsum enim consectetur qui non cillum aute incididunt dolore. Esse magna exercitation quis consequat minim. Enim minim duis do non occaecat eu qui ea velit incididunt elit commodo.\r\n',
    registered: '2015-05-01T06:29:13 -08:00',
    latitude: 70.686571,
    longitude: 73.67665,
    tags: ['ut', 'incididunt', 'ut', 'est', 'aliquip', 'sint', 'laborum'],
    friends: [
      {
        id: 0,
        name: 'Marcy Nixon',
      },
      {
        id: 1,
        name: 'Dana Mcgowan',
      },
      {
        id: 2,
        name: 'Alexander Kirkland',
      },
    ],
    greeting: 'Hello, Gallegos Good! You have 3 unread messages.',
    favoriteFruit: 'strawberry',
  },
]
